name: kdmp_cm_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Networking
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1

  # State Management
  provider: ^6.0.5

  # Dependency Injection
  get_it: ^7.6.0

  # Route
  go_router: ^10.1.2

  # Local Storage
  flutter_secure_storage: ^9.0.0

  # Permission
  permission_handler: ^10.4.3

  # Toast Message
  fluttertoast: ^8.2.2

  # Geo Location
  geolocator: ^10.0.0

  # HTML
  flutter_html: ^3.0.0-beta.1

  # URL Launcher
  url_launcher: ^6.1.14

  # Device Info
  device_info_plus: ^9.0.3
  android_id: ^0.3.5

  # For MediaType
  http_parser: ^4.0.2

  # For DateFormat
  intl: ^0.18.1

  # On Boarding
  introduction_screen: ^3.0.2

  # 다국어 패키지
  flutter_localizations:
    sdk: flutter

  # Naver Map
  flutter_naver_map: ^1.0.2

  # 키 관리
  flutter_dotenv: ^5.1.0

  # Wheel Chooser
  wheel_chooser: ^1.1.2

  # Firebase Messaging
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0

  # IP Info
  get_ip_address: ^0.0.6

  # UUID
  uuid: ^4.1.0

  # Indicator
  smooth_page_indicator: ^1.1.0

  # App Info
  package_info_plus: ^4.2.0

  # WebView
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # App Icon
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/app_icon.png
    - assets/common/app_logo_light.png
    - assets/common/app_logo_dark.png
    - assets/common/icon_warning.png
    - assets/common/img_warning.png
    - assets/common/ic_start.png
    - assets/common/ic_end.png
    - assets/common/img_money.png
    - assets/common/img_car.png
    - assets/setup/icon_darkmode.png
    - assets/setup/icon_lightmode.png
    - assets/permission/icon_call.png
    - assets/permission/icon_file.png
    - assets/permission/icon_location.png
    - assets/permission/icon_notification.png
    - assets/register/icon_check_off.png
    - assets/register/icon_check_on.png
    - assets/register/img_no_permission.png
    - assets/menu/icon_called_light.png
    - assets/menu/icon_car_info_light.png
    - assets/menu/icon_cs_light.png
    - assets/menu/icon_mypage_light.png
    - assets/menu/icon_payment_light.png
    - assets/menu/icon_place_light.png
    - assets/menu/icon_setup_light.png
    - assets/menu/icon_terms_light.png
    - assets/menu/icon_called_dark.png
    - assets/menu/icon_car_info_dark.png
    - assets/menu/icon_cs_dark.png
    - assets/menu/icon_mypage_dark.png
    - assets/menu/icon_payment_dark.png
    - assets/menu/icon_place_dark.png
    - assets/menu/icon_setup_dark.png
    - assets/menu/icon_terms_dark.png
    - assets/menu/icon_car.png
    - assets/work/img_work.png
    - assets/onboarding/img_onboarding1_light.png
    - assets/onboarding/img_onboarding1_dark.png
