// Mocks generated by Mockito 5.4.6 from annotations
// in kdmp_cm_app/test/presentation/viewmodel/mypage/call_detail_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kdmp_cm_app/data/model/common/drv_request.dart' as _i6;
import 'package:kdmp_cm_app/data/model/common/state.dart' as _i2;
import 'package:kdmp_cm_app/data/model/fcm/fcm_push_request.dart' as _i12;
import 'package:kdmp_cm_app/data/model/work/call_cancel_request.dart' as _i8;
import 'package:kdmp_cm_app/data/model/work/confirm_call_cancel_request.dart'
    as _i10;
import 'package:kdmp_cm_app/domain/usecase/fcm/set_fcm_push_usecase.dart'
    as _i11;
import 'package:kdmp_cm_app/domain/usecase/mypage/get_call_detail_usecase.dart'
    as _i5;
import 'package:kdmp_cm_app/domain/usecase/secure_storage/mbr/get_mbrsq_usecase.dart'
    as _i3;
import 'package:kdmp_cm_app/domain/usecase/work/set_call_cancel_usecase.dart'
    as _i7;
import 'package:kdmp_cm_app/domain/usecase/work/set_confirm_call_cancel_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStateAPI_0 extends _i1.SmartFake implements _i2.StateAPI {
  _FakeStateAPI_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMbrSqUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMbrSqUseCase extends _i1.Mock implements _i3.GetMbrSqUseCase {
  MockGetMbrSqUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [GetCallDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCallDetailUseCase extends _i1.Mock
    implements _i5.GetCallDetailUseCase {
  MockGetCallDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StateAPI> execute(
          {required _i6.DrvRequest? callDetailRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#callDetailRequest: callDetailRequest},
        ),
        returnValue: _i4.Future<_i2.StateAPI>.value(_FakeStateAPI_0(
          this,
          Invocation.method(
            #execute,
            [],
            {#callDetailRequest: callDetailRequest},
          ),
        )),
      ) as _i4.Future<_i2.StateAPI>);
}

/// A class which mocks [SetCallCancelUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetCallCancelUseCase extends _i1.Mock
    implements _i7.SetCallCancelUseCase {
  MockSetCallCancelUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StateAPI> execute(
          {required _i8.CallCancelRequest? callCancelRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#callCancelRequest: callCancelRequest},
        ),
        returnValue: _i4.Future<_i2.StateAPI>.value(_FakeStateAPI_0(
          this,
          Invocation.method(
            #execute,
            [],
            {#callCancelRequest: callCancelRequest},
          ),
        )),
      ) as _i4.Future<_i2.StateAPI>);
}

/// A class which mocks [SetConfirmCallCancelUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetConfirmCallCancelUseCase extends _i1.Mock
    implements _i9.SetConfirmCallCancelUseCase {
  MockSetConfirmCallCancelUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StateAPI> execute(
          {required _i10.ConfirmCallCancelRequest? confirmCallCancelRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#confirmCallCancelRequest: confirmCallCancelRequest},
        ),
        returnValue: _i4.Future<_i2.StateAPI>.value(_FakeStateAPI_0(
          this,
          Invocation.method(
            #execute,
            [],
            {#confirmCallCancelRequest: confirmCallCancelRequest},
          ),
        )),
      ) as _i4.Future<_i2.StateAPI>);
}

/// A class which mocks [SetFCMPushUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetFCMPushUseCase extends _i1.Mock implements _i11.SetFCMPushUseCase {
  MockSetFCMPushUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StateAPI> execute(
          {required _i12.FCMPushRequest? fcmPushRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#fcmPushRequest: fcmPushRequest},
        ),
        returnValue: _i4.Future<_i2.StateAPI>.value(_FakeStateAPI_0(
          this,
          Invocation.method(
            #execute,
            [],
            {#fcmPushRequest: fcmPushRequest},
          ),
        )),
      ) as _i4.Future<_i2.StateAPI>);
}
